INSERT INTO departments (name)
VALUES 
    ("HR"),
    ("Front End"),
    ("Production"),
    ("Managment"),
    ("Backend"),
    ("Marketing");

INSERT INTO roles (title, salary, department_id)
VALUES 
    ("Therapist", 500.00, 1),
    ("UI Designer", 10.00, 2),
    ("Chair-Setter", 10000.00, 3),
    ("Attendance Taker", 10001.00, 3),
    ("Conductor", 65.00, 4),
    ("Query Maker", 65.00, 5),
    ("Mediator", 56700.00, 6),
    ("Finsta Post Maker", 2.00, 6);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES
  ('James', 'Fraser', '1', '7'),
  ('Jack', 'London', '1', '7'),
  ('Robert', 'Bruce', '1', '7'),
  ('Peter', 'Greenaway', '1', '7'),
  ('Derek', 'Jarman', '1', '7'),
  ('Paolo', 'Pasolini', '2', '7'),
  ('Heathcote', 'Williams', '2', '3'),
  ('Sandy', 'Powell', '2', '3'),
  ('Emil', 'Zola', '2', '3'),
  ('Sissy', 'Coalpits', '2', '3'),
  ('Antoinette', 'Capet', '2', '3'),
  ('Samuel', 'Delany', '2', '3'),
  ('Tony', 'Duvert', '2', '3'),
  ('Dennis', 'Cooper', '2', '3'),
  ('Monica', 'Bellucci', '2', '3'),
  ('Samuel', 'Johnson', '1', '7'),
  ('John', 'Dryden', '1', '7'),
  ('Alexander', 'Pope', '1', null),
  ('Lionel', 'Johnson', '1', null),
  ('Aubrey', 'Beardsley', '1', null),
  ('Tulse', 'Luper', '1', null),
  ('William', 'Morris', '1', null),
  ('George', 'Shaw', '1', null),
  ('Arnold', 'Bennett', '1', null),
  ('Algernon', 'Blackwood', '1', null),
  ('Rhoda', 'Broughton', '1', '7'),
  ('Hart', 'Crane', '4', '7'),
  ('Vitorio', 'DeSica', '4', '7'),
  ('Wilkie', 'Collins', '4', '7'),
  ('Elizabeth', 'Gaskell', '4', '7'),
  ('George', 'Sand', '4', '7'),
  ('Vernon', 'Lee', '4', '7'),
  ('Arthur', 'Machen', '4', '7'),
  ('Frederick', 'Marryat', '4', '7'),
  ('Harriet', 'Martineau', '4', '7'),
  ('George', 'Meredith', '1', '7'),
  ('Margaret', 'Oliphant', '1', '7'),
  ('Anthony', 'Trollope', '6', '7'),
  ('Charlotte', 'Yonge', '6', '7'),
  ('Horace', 'Walpole', '6', '7'),
  ('Matthew', 'Lewis', '6', '7'),
  ('William', 'Bedford', '6', '7'),
  ('Anne', 'Radcliffe', '6', '7'),
  ('Charles', 'Brown', '6', '7'),
  ('Eliza', 'Parsons', '1', '7'),
  ('Susan', 'Hill', '1', '7'),
  ('Sydney', 'Owenson', '1', '7'),
  ('Hubert', 'Crackanthorpe', '1', '7'),
  ('William', 'Carleton', '1', '7'),
  ('Gerald', 'Griffin', '1', '7');
